app/carts/urls.py
from django.urls import path

from carts.views import CartAddView, CartChangeView, CartRemoveView

app_name='carts'

urlpatterns = [
    path('cart_add/', CartAddView.as_view(), name='cart_add'),
    path('cart_change/', CartChangeView.as_view(), name ='cart_change' ),
    path('cart_remove/', CartRemoveView.as_view(), name ='cart_remove' ),
]

app/config/urls.py
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/goods/urls.py
from django.urls import path

from goods.views import CatalogView, ProductView

app_name='goods'

urlpatterns = [
    path('search/', CatalogView.as_view(), name='search'),
    path('<slug:category_slug>/', CatalogView.as_view(), name='index'),
    path('product/<slug:product_slug>/', ProductView.as_view(), name ='product' ),
]

app/main/urls.py
from django.urls import path

from main import views

app_name='main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name ='about' ),
]

app/orders/urls.py
from django.urls import path

from orders.views import CreateOrderView

app_name='orders'

urlpatterns = [
    path('create_order/', CreateOrderView.as_view(), name='create_order'),
]

app/users/urls.py
from django.urls import path

from users.views import UserLoginView, UserProfileView, UserRegistrationView, UserCartView, logout

app_name='users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('user_cart/', UserCartView.as_view(), name='user_cart'),
    path('logout/', logout, name='logout'),
]

app/templates/includes/cart_button.html
{% load static %}
{% load carts_tags %}

{% user_carts request as carts %}

<div>
    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
        aria-expanded="false">
        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
            height="24">
        <span id="goods-in-cart-count">{{ carts.total_amount }}</span>
    </button>
</div>
<!-- Разметка модального окна корзины -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "includes/included_cart.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/includes/catalog_button.html
{% load static %}
{% load cache %}
{% load goods_tags %}

<div class="dropdown mb-2">
    <button class="btn custom-btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
        aria-expanded="false">
        Каталог
        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
            height="16">
    </button>
    <ul class="dropdown-menu bg-custom" data-bs-theme="dark">
        {% cache 60 catalog_categories %}
        {% tag_categories as categories %}
        {% for category in categories %}
        <li>
            <a class="dropdown-item text-white" href="{% url "catalog:index" category.slug%}">{{category.name}}</a>
        </li>
        {% endfor %}
        {% endcache %}
    </ul>
</div>

app/templates/includes/header.html
{% load static %}
{% load goods_tags %}

<nav class="navbar navbar-expand-lg bg-collor" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="{% url "main:index" %}">
            <img src="{% static "/deps/images/image_2.png" %}" width="" height="64">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown ">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Информация
                    </a>
                    <ul class="dropdown-menu bg-custom">
                        <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                        <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                        <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">Про нас</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link  text-white" href="{% url "user:user_cart" %}">Корзина</a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link  text-white" href="{% url "user:login" %}">Войти</a>
                </li>
                {% else %}
                <li class="nav-item dropdown ">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">Мой профиль</a>
                    <ul class="dropdown-menu bg-custom">
                        <li><a class="dropdown-item  text-white" href="{% url "user:user_cart" %}">Корзина</a></li>
                        <li><a class="dropdown-item  text-white" href="{% url "user:profile" %}">Личный кабинет</a></li>
                        {% if user.is_admin or user.is_staff %}
                            <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                        {% endif %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Выйти</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
                <input class="form-control me-2" type="search" name="q" placeholder="Поиск по сайту" aria-label="Search">
                <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
            </form>
        </div>
    </div>
</nav>

app/templates/includes/included_cart.html
{% load static %}

<div class="card mb-3 text-bg-light shadow-lg">
    {% for cart in carts %}
        <div class="card-header">
            <h5 class="card-title">{{ cart.product.name }}</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row text-center">
                    <div class="col p-0">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm decrement"
                                data-cart-id="{{ cart.id }}"
                                data-cart-change-url="{% url "cart:cart_change" %}">
                                {% csrf_token %}
                                -</button>
                            </span>
                            <input type="text" class="form-control number" value="{{ cart.amount }}"
                                readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm increment"
                                data-cart-id="{{ cart.id }}"
                                data-cart-change-url="{% url "cart:cart_change" %}">
                                {% csrf_token %}
                                +</button>
                            </span>
                        </div>
                    </div>
                    <div class="col p-0">
                        <p>x {{ cart.product.sell_price }} = </p>
                    </div>
                    <div class="col p-0"><strong> {{cart.products_price}} руб. </strong></div>
                    <div class="col p-0">
                        <a href="{% url "cart:cart_remove" %}" class="remove-from-cart" data-cart-id="{{ cart.id }}">
                        {% csrf_token %}
                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                alt="Catalog Icon" width="16" height="16">
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}
</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">Итого <strong>{{ carts.total_amount }}</strong> товар(а) на сумму</p>
        <h4 class="float-left"><strong>{{ carts.total_price }} руб. </strong></h4>
    </div>
</div>


{% if carts and not order%}
    <a class="btn btn-dark" href="{% url "orders:create_order" %}">
        Оформить заказ
    </a>
{% endif %}

app/templates/includes/notifications.html
{% load static %}

{% if form.non_field_errors %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                    {{form.non_field_errors}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
            <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
            </div>
            {% endif %}
        </div>
    </div>
</div>

app/templates/includes/pagination.html
{% load static %}
{% load goods_tags %}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %} ">
              <a class="page-link" href="
              {% if page_obj.has_previous %}?{% change_params page=1%}{% else %}#{% endif %}">Первая</a>
            </li>

            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %} ">
              <a class="page-link" href="
              {% if page_obj.has_previous %}?{% change_params page=page_obj.previous_page_number%}{% else %}#{% endif %}">Назад</a>
            </li>
            {% for page in page_obj.paginator.page_range %}
            {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
            <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                <a class="page-link" href="?{% change_params page=page%}">{{page}}</a></li>
            {% endif %}
            {% endfor %}
            
            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %} ">
                <a class="page-link" href="
                {% if page_obj.has_next %}?{% change_params page=page_obj.next_page_number%}{% else %}#{% endif %}">Следующая</a>
            </li>
              
            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %} ">
                <a class="page-link" href="
                {% if page_obj.has_next %}?{% change_params page=page_obj.paginator.num_pages %}{% else %}#{% endif %}">Последняя</a>
            </li>    
        </div>
    </ul>
</nav>

app/templates/includes/product_card.html
{% load static %}

<div class="col-lg-4 col-md-6 p-4">
    <div class="card border-primary rounded custom-shadow">
        {% if product.image %}
        <img src="{{product.image.url}}" class="card-img-top" alt="{{product.name}}">
        {% else %}
        <img src="{% static "deps/images/Not found image.png" %}" class="card-img-top" alt="...">
        {% endif %}
        <div class="card-body">
            <a href="{% url "catalog:product" product.slug%}">
                <p class="card-title">
                    {% autoescape off %}
                        {% if product.headline %}
                        {{product.headline}}
                        {% else %}
                        {{ product.name }}
                        {% endif %}
                    {% endautoescape %}
                </p>
            </a>
            <p class="card-text text-truncate">
                {% autoescape off %}
                    {% if product.bodyline %}
                    {{product.bodyline}}
                    {% else %}
                    {{ product.description}}
                    {% endif %}
                {% endautoescape %}</p>
            <div class="d-flex justify-content-between">
                {% if product.discount %}
                <p><s>{{product.sell_price}}</s> руб. </p>
                <p><strong>{{product.sell_price}} руб. </strong></p>
                <span class="badge bg-warning text-dark">Скидка {{product.discount}} %</span>
                {% else %}
                <p><strong>{{product.sell_price}} руб. </strong></p>
                {% endif %}
                <a href="{% url "cart:cart_add"%}" class="btn add-to-cart" data-product-id="{{ product.id }}">
                    {% csrf_token %}
                    <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                        width="32" height="32">
                </a>
            </div>
        </div>
    </div>
</div>